#!/bin/bash

# 13 Aguila_Imperial

mkdir Aguila_Imperial
cd Aguila_Imperial
for i in {0..2}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 262 ]
            then
                url="https://api.myl.cl/static/cards/13/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..