#!/bin/bash

# 23 (32) Arsenal

mkdir Arsenal
cd Arsenal
for i in {0..1}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 122 ]
            then
                url="https://api.myl.cl/static/cards/32/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..