#!/bin/bash

# 05 Asgard

mkdir Asgard
cd Asgard
for i in {1..2}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 237 ]
            then
                url="https://api.myl.cl/static/cards/05/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..