#!/bin/bash

# 07 Camelot

mkdir Camelot
cd Camelot
for i in {0..2}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 238 ]
            then
                url="https://api.myl.cl/static/cards/07/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..