#!/bin/bash

# 12 Contraataque

mkdir Contraataque
cd Contraataque
for i in {0..1}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 151 ]
            then
                url="https://api.myl.cl/static/cards/12/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..