#!/bin/bash

# 22 (31) Kilimanjaro

mkdir Kilimanjaro
cd Kilimanjaro
for i in {0..2}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 277 ]
            then
                url="https://api.myl.cl/static/cards/31/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..