#!/bin/bash

# 17 Legado_Gotico

mkdir Legado_Gotico
cd Legado_Gotico
for i in {0..2}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 260 ]
            then
                url="https://api.myl.cl/static/cards/17/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..