#!/bin/bash

# 10 Sol_Naciente

mkdir Sol_Naciente
cd Sol_Naciente
for i in {0..1}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 143 ]
            then
                url="https://api.myl.cl/static/cards/10/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..