#!/bin/bash

# 03 Sumeria

mkdir Sumeria
cd Sumeria
for i in {2..3}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 221 ]
            then
                url="https://api.myl.cl/static/cards/03/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..