#!/bin/bash

# 24 (33) Tinta_Inmortal

mkdir Tinta_Inmortal
cd Tinta_Inmortal
for i in {0..1}
do
    for j in {0..9}
    do
        for k in {0..9}
        do
            let item=$i*100+$j*10+$k
            if [ $item -lt 106 ]
            then
                url="https://api.myl.cl/static/cards/33/"$i$j$k".png"
                wget $url --no-check-certificate
            fi
        done
    done
done
cd ..